import './globals.css'
import {Roboto} from 'next/font/google'
import Providers from "@/utils";

const roboto = Roboto({
    subsets: ['latin'],
    weight: ["400", "500", "700"]
})

export const metadata = {
    title: 'Next Blog',
    description: 'Generated by create next app',
}
export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={`${roboto.className} min-h-screen container mx-auto px-3`}
              suppressHydrationWarning={true}>
        <Providers>
            {children}
        </Providers>
        </body>
        </html>
    )
}
